# Generated by Django 3.1.7 on 2021-03-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delete_deliveryinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPrice',
        ),
    ]
