# Generated by Django 3.2 on 2021-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profileinformation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinformation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
