# Generated by Django 3.2 on 2021-04-20 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profileinformation_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinformation',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profileinformation',
            name='email',
            field=models.EmailField(default='Empty', max_length=254),
        ),
        migrations.AlterField(
            model_name='profileinformation',
            name='gender',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileinformation',
            name='name',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileinformation',
            name='phone_number',
            field=models.CharField(blank=True, default='Empty', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profileinformation',
            name='surname',
            field=models.CharField(blank=True, default='Empty', max_length=255, null=True),
        ),
    ]
