# Generated by Django 3.1.7 on 2021-03-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMealPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='ingredient_images')),
                ('allergen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_ingredients', models.CharField(max_length=300)),
                ('meal_picture', models.ImageField(blank=True, null=True, upload_to='recipes_images')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('origin', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('M&V', 'Meat and Veggie'), ('VRN', 'Vegetarian'), ('VGN', 'Vegan')], max_length=255)),
                ('description', models.TextField(max_length=600)),
                ('cooking_time', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('base_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.basemealprice')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='steps_images')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
