# Generated by Django 3.1.7 on 2021-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_addingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addingredient',
            name='ingredient',
            field=models.CharField(choices=[('Tomato', 'Tomato'), ('Pasta', 'Pasta'), ('Beef', 'Beef'), ('Olive oil', 'Olive oil'), ('Chipotle Beans', 'Chipotle Beans'), ('Oregano', 'Oregano'), ('Tomato Paste', 'Tomato Paste'), ('Mayonnaisse', 'Mayonnaisse'), ('Parmesan', 'Parmesan'), ('Tortilla', 'Tortilla'), ('Iceberg salad', 'Iceberg salad')], max_length=255),
        ),
    ]
