# Generated by Django 3.2 on 2021-04-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_addingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addingredient',
            name='ingredient',
            field=models.CharField(choices=[('Apple & Sage Jelly', 'Apple & Sage Jelly'), ('Asparagus', 'Asparagus'), ('Aubergine', 'Aubergine'), ('Avocado', 'Avocado'), ('Baby Gem Lettuce', 'Baby Gem Lettuce'), ('Baby Plum Tomatoes', 'Baby Plum Tomatoes'), ('Balsamic Vinegar', 'Balsamic Vinegar'), ('Basmati Rice', 'Basmati Rice'), ('BBQ Sauce', 'BBQ Sauce'), ('Beef', 'Beef'), ('Bell Pepper', 'Bell Pepper'), ('Broccoli', 'Broccoli'), ('Burger Bun', 'Burger Bun'), ('Carrots', 'Carrots'), ('Chedar Cheese', 'Chedar Cheese'), ('Chesnut Mushrooms', 'Chesnut Mushrooms'), ('Chicken Stock Powder', 'Chicken Stock Powder'), ('Chicken Thigh', 'Chicken Thigh'), ('Chickpeas', 'Chickpeas'), ('Chipotle Beans', 'Chipotle Beans'), ('Chipotle Paste', 'Chipotle Paste'), ('Chives', 'Chives'), ('Chorizo', 'Chorizo'), ('Ciabatta', 'Ciabatta'), ('Cider Vinegar', 'Cider Vinegar'), ('Coconut Milk', 'Coconut Milk'), ('Coleslow Mix', 'Coleslow Mix'), ('Coriander', 'Coriander'), ('Courgette', 'Courgette'), ('Creme Fraiche', 'Creme Fraiche'), ('Cucumber', 'Cucumber'), ('Diced Butternut Squash', 'Diced Butternut Squash'), ('Diced Chicken Thigh', 'Diced Chicken Thigh'), ('Echalion Shallot', 'Echalion Shallot'), ('Egg Noodle Nest', 'Egg Noodle Nest'), ('Finely Chopped Tomatoes', 'Finely Chopped Tomatoes'), ('Flat Leaf Parsley', 'Flat Leaf Parsley'), ('Ginged Puree', 'Ginged Puree'), ('Green Beans', 'Green Beans'), ('Ground Cumin', 'Ground Cumin'), ('Halloumi Cheese', 'Halloumi Cheese'), ('Honey', 'Honey'), ('Honey Mustard Sauseges', 'Honey Mustard Sauseges'), ('Iceberg salad', 'Iceberg salad'), ('Italian Herbs', 'Italian Herbs'), ('Kale', 'Kale'), ('Ketjap Panis', 'Ketjap Panis'), ('Leek', 'Leek'), ('Lemon', 'Lemon'), ('Lime', 'Lime'), ('Linguine', 'Linguine'), ('Mangetout', 'Mangetout'), ('Mayonnaisse', 'Mayonnaisse'), ('Mixed Beans', 'Mixed Beans'), ('Mozzarella', 'Mozzarella'), ('Olive oil', 'Olive oil'), ('Onion', 'Onion'), ('Oregano', 'Oregano'), ('Panko Breadcrumbs', 'Panko Breadcrumbs'), ('Parmesan', 'Parmesan'), ('Peanut Butter', 'Peanut Butter'), ('Pene Pasta', 'Pene Pasta'), ('Plain Flour', 'Plain Flour'), ('Pork and Oregano Sausage Meat', 'Pork and Oregano Sausage Meat'), ('Pork Lion Steak', 'Pork Lion Steak'), ('Portobello Mushroom', 'Portobello Mushroom'), ('Potato', 'Potato'), ('Provencal Herbs', 'Provencal Herbs'), ('Red Chilli', 'Red Chilli'), ('Red Onion', 'Red Onion'), ('Red Split Lentils', 'Red Split Lentils'), ('Red Wine Jus Paste', 'Red Wine Jus Paste'), ('Red Wine Stock Paste', 'Red Wine Stock Paste'), ('Red Wine Vinegar', 'Red Wine Vinegar'), ('Rice Vinegas', 'Rice Vinegas'), ('Rigatoni Pasta', 'Rigatoni Pasta'), ('Risoto Rice', 'Risoto Rice'), ('Rocket', 'Rocket'), ('Salted Peanuts', 'Salted Peanuts'), ('Shiitake Mushrooms', 'Shiitake Mushrooms'), ('Shredded Savoy Cabbage', 'Shredded Savoy Cabbage'), ('Sliced Mushrooms', 'Sliced Mushrooms'), ('Smoked Paprika', 'Smoked Paprika'), ('Soft Shell Taco', 'Soft Shell Taco'), ('Soy Sauce', 'Soy Sauce'), ('Spaghetti', 'Spaghetti'), ('Spring Onion', 'Spring Onion'), ('Sriracha', 'Sriracha'), ('Steaky Bacon Rashers', 'Steaky Bacon Rashers'), ('Sun-Dried Tomato Paste', 'Sun-Dried Tomato Paste'), ('Sweet Chilli Sauce', 'Sweet Chilli Sauce'), ('Sweet Corn', 'Sweet Corn'), ('Tomato', 'Tomato'), ('Tomato Paste', 'Tomato Paste'), ('Tomato Ketchup', 'Tomato Ketchup'), ('Tomato Puree', 'Tomato Puree'), ('Tortilla', 'Tortilla'), ('Vegetable Stock Paste', 'Vegetable Stock Paste'), ('Wholegrain Mustard', 'Wholegrain Mustard'), ('Wholemeal Tortilla', 'Wholemeal Tortilla'), ('Wooden Skewers', 'Wooden Skewers'), ('Worcester Sauce', 'Worcester Sauce'), ('Yellow Curry Paste', 'Yellow Curry Paste'), ('Truffle Powder', 'Truffle Powder'), ('Sweet Potato', 'Sweet Potato'), ('Mexican Style Spice', 'Mexican Style Spice'), ('Feta Cheese', 'Feta Cheese'), ('Tenderstem Broccoli', 'Tenderstem Broccoli'), ('Walnuts', 'Walnuts')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Meat and Veggie', 'Meat and Veggie'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], max_length=255),
        ),
    ]
