# Generated by Django 3.1.7 on 2021-03-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientquantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientQuantity',
            new_name='AddIngredient',
        ),
    ]
