# Generated by Django 3.1.7 on 2021-03-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210322_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.CharField(choices=[(2, 'Tomato'), (3, 'Pasta')], max_length=10),
        ),
    ]
