# Generated by Django 3.1.7 on 2021-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210328_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_time_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
