# Generated by Django 3.1.7 on 2021-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210322_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_picture',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
