# Generated by Django 3.1.7 on 2021-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_meal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.CharField(choices=[('2', 'Tomato'), ('3', 'Pasta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('M&V', 'Meat and Veggie'), ('VRN', 'Vegetarian'), ('VGN', 'Vegan')], max_length=20),
        ),
    ]
