# Generated by Django 3.1.7 on 2021-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='recipe',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
