# Generated by Django 3.1.7 on 2021-03-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_size', models.CharField(choices=[('2P', 'Meal for 2'), ('3P', 'Meal for 3'), ('4P', 'Meal for 4'), ('5P', 'Meal for 5')], max_length=2)),
                ('number_of_meals', models.CharField(choices=[('2', '2 day program'), ('3', '3 day program'), ('4', '4 day program'), ('5', '5 day program')], max_length=1)),
            ],
        ),
    ]
