# Generated by Django 3.1.7 on 2021-03-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_chosenmeals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chosenmeals',
            old_name='meal',
            new_name='meal_id',
        ),
    ]
