# Generated by Django 3.1.7 on 2021-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210323_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='meal_size',
            field=models.IntegerField(choices=[(2, 'Meal for 2'), (3, 'Meal for 3'), (4, 'Meal for 4'), (5, 'Meal for 5')], default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='number_of_meals',
            field=models.IntegerField(choices=[(2, '2 day program'), (3, '3 day program'), (4, '4 day program'), (5, '5 day program')], default=0),
        ),
    ]
