# Generated by Django 3.1.7 on 2021-03-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210328_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='box',
            name='single_meal_price',
        ),
    ]
