# Generated by Django 3.1.7 on 2021-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210401_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinformation',
            name='phone_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
