# Generated by Django 3.1.7 on 2021-04-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_deliveryinformation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
