# Generated by Django 3.1.7 on 2021-04-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
        ('orders', '0010_auto_20210401_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chosemeals',
            name='box',
        ),
        migrations.RemoveField(
            model_name='chosemeals',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boxes.box'),
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.DeleteModel(
            name='ChoseMeals',
        ),
    ]
